version: "3.3"

services:
####################################### NGINX #########################################
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ./wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
####################################### MARIADB #########################################
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        DB_DATABASE: mariadb
        DB_ROOT_PASSWORD: inception
        DB_USER: tintin
        DB_USER_PASSWORD: milou
        DB_HOST: mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - ./mariadb:/var/lib/mariadb
    networks:
      - inception
    restart: always
####################################### WORDPRESS #########################################
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always
####################################### NETWORKS #######################################
networks:
  inception:
    driver: bridge
    name: inception
####################################### VOLUMES ########################################
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/dvallien/data/mariadb
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/dvallien/data/wordpress